version: '3.8'

services:
  web:
    build: ./
    environment:
      - MONGODB_URI=mongodb+srv://admin:Killmenow111@jwt-auth.xlcbf.mongodb.net/growminose?retryWrites=true&w=majority
    ports:
      - 3000:3000