import Head from "next/head";
import styles from "../styles/Home.module.css";
import Slider from "../comps/Slider";
import PizzaList from "../comps/PizzaList";
import axios from "axios";

export default function Home({ pizzas }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      <PizzaList pizzaList={pizzas} />
      homepage
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/product");
  console.log(res, "===+++===");
  return {
    props: {
      pizzas: res.data,
    },
  };
};
