import Head from "next/head";
import styles from "../styles/Home.module.css";
import Slider from "../comps/Slider";
import PizzaList from "../comps/PizzaList";
import axios from "axios";

export default function Home({ pizzas }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      <PizzaList pizzaList={pizzas} />
      homepage
    </div>
  );
}

export const getServerSideProps = async ({ req }) => {
  const protocol = req.headers["x-forwarded-proto"] || "http";
  const domain = req.headers.host;
  const fullUrl = `${protocol}://${domain}`;
  const res = await axios.get(`${fullUrl}/api/product`);

  return {
    props: {
      pizzas: res.data,
    },
  };
};
